nameOverride: ""
fullnameOverride: ""


upf:
  name: upf
  app: open5gs
  replicaCount: 1
  image:
    registry: boubasse
    name: open5gs
    pullPolicy: Always
    tag: upf
  
  n4ip: 10.100.50.241
  n3ip: 10.1.2.3
  n6ip: 10.10.30.208

  ue:
    max: 1024
    subnet4: 10.45.0.1/16
    tun4: 10.45.0.0/16
    subnet6: 2001:db8:cafe::1/48
  
  n3network:
    enabled: true
    name: n3network
    type: host-device
    masterIf: ens21
    subnetIP: 10.1.2.0
    cidr: 24
    gatewayIP: 10.1.2.254
    excludeIP: 10.1.2.254
  n4network:
    enabled: true
    name: n4network
    type: ipvlan
    masterIf: ens18
    subnetIP: 10.100.50.240
    cidr: 29
    gatewayIP: 10.100.50.246
    excludeIP: 10.100.50.246
  n6network:
    enabled: true
    name: n6network
    type: host-device
    masterIf: ens19
    subnetIP: 10.10.30.0
    cidr: 24
    gatewayIP: 10.10.30.254
    excludeIP: 10.10.30.254

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext:
    privileged: true
    capabilities:
        add: ["NET_ADMIN", "NET_RAW"]
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  volumeMounts:
    confPath: "/open5gs/install/etc"
    logPath: "/open5gs/install/log"
  
  logger:
    file: /open5gs/install/log/upf.log
    level: info
