{{- with .Values.nssf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs-nssf.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.name }}
data:
  nssf.yaml: |
    logger:
      {{- toYaml .logger | nindent 8 }}
    global:
      max:
        ue: {{ $.Values.global.ue.max }} # The number of UE can be increased depending on memory size.
    #    peer: 64

    nssf:
      sbi:
        server:
          - address: 0.0.0.0
            port: {{ .service.port }}
            advertise: {{ include "open5gs-nssf.fullname" $ }}-sbi
        client:
    #      nrf:
    #        - uri: http://127.0.0.10:7777
          scp:
            - uri: http://{{ $.Values.global.scp.service.name }}:{{ $.Values.global.scp.service.port }}
          nsi:
            - uri: http://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}
              s_nssai:
                sst: 1
{{- end }}
