{{- with .Values.scp }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs-scp.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.name }}
data:
  scp.yaml: |
    logger:
      {{- toYaml .logger | nindent 8 }}
    global:
      max:
        ue: {{ $.Values.global.ue.max }} # The number of UE can be increased depending on memory size.
    #    peer: 64

    scp:
      # no_sepp: true
      sbi:
        server:
          - address: {{ .sbinet.ip }}
            port: {{ .sbinet.port }}
        client:
         nrf:
           - uri: http://{{ $.Values.global.nrf.sbinet.ip }}:{{ $.Values.global.nrf.sbinet.port }}
{{- end }}
