{{- with .Values.scp}}
{{- if .service.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.global.scp.service.name }}
  labels:
    {{- include "open5gs-scp.labels" $ | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ $.Values.global.scp.service.port }}
      targetPort: {{ $.Values.global.scp.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "open5gs-scp.selectorLabels" $ | nindent 4 }}
{{- end}}
{{- end}}