{{- with .Values.pcf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs-pcf.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.name }}
data:
  pcf.yaml: |
    db_uri: {{ $.Values.global.db_uri }}
    logger:
      {{- toYaml .logger | nindent 8 }}
    global:
      max:
        ue: {{ $.Values.global.ue.max }} # The number of UE can be increased depending on memory size.
    #    peer: 64

    pcf:
      sbi:
        server:
          - address: 0.0.0.0
            port: {{ .service.port }}
            advertise: {{ include "open5gs-pcf.fullname" $ }}-sbi
        client:
    #      nrf:
    #        - uri: http://127.0.0.10:7777
          scp:
            - uri: http://{{ $.Values.global.scp.service.name }}:{{ $.Values.global.scp.service.port }}
{{- end }}
