{{- with .Values.pcf}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs-pcf.fullname" $ }}-sbi
  labels:
    {{- include "open5gs-pcf.labels" $ | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "open5gs-pcf.selectorLabels" $ | nindent 4 }}
{{- end}}