{{- with .Values.ausf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs-ausf.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.name }}
data:
  ausf.yaml: |
    logger:
      {{- toYaml .logger | nindent 8 }}
    global:
      max:
        ue: {{ $.Values.global.ue.max }} # The number of UE can be increased depending on memory size.
    #    peer: 64

    ausf:
      sbi:
        server:
          - address: {{ .sbinet.ip }}
            port: {{ .sbinet.port }}
        client:
    #      nrf:
    #        - uri: http://127.0.0.10:7777
          scp:
            - uri: http://{{ $.Values.global.scp.sbinet.ip }}:{{ $.Values.global.scp.sbinet.port }}
{{- end }}
