{{- with .Values.ausf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open5gs-ausf.fullname" $ }}
  labels:
    {{- include "open5gs-ausf.labels" $ | nindent 4 }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "open5gs-ausf.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "open5gs-ausf.labels" $ | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      
      initContainers:
      - name: wait-scp
        {{- with $.Values.global.initcontainers.curl }}
        image: {{ .registry }}/{{ .image }}:{{ .tag }}
        {{- end }}
        imagePullPolicy: {{ .image.pullPolicy }}
        env:
        - name: URIS
          value: http://{{ $.Values.global.scp.service.name }}:{{ $.Values.global.scp.service.port }}
        command: ['sh', '-c', 'set -x; for uri in $URIS; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $uri --http2-prior-knowledge) -ne 400 ]; do echo waiting for scp; sleep 1; done; done;']
      containers:
      - name: {{ .name }}
        securityContext:
          {{- toYaml .securityContext | nindent 12 }}
        image: "{{ .image.registry }}/{{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - name: ausf-sbi
          containerPort: {{ .service.port }}
        resources:
          {{- toYaml .resources | nindent 12 }}
        volumeMounts:
        - mountPath: {{ .volumeMounts.confPath }}
          name: {{ include "open5gs-ausf.fullname" $ }}-conf-volume
        - mountPath: {{ .volumeMounts.logPath }}
          name: {{ include "open5gs-ausf.fullname" $ }}-log-volume
        command: ["./open5gs-ausfd"]
        args: ["-c", "../etc/ausf.yaml"]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
         {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ include "open5gs-ausf.fullname" $ }}-log-volume
        emptyDir: {}
      - name: {{ include "open5gs-ausf.fullname" $ }}-conf-volume
        projected:
          sources:
          - configMap:
              name: {{ include "open5gs-ausf.fullname" $ }}-configmap
{{- end }}