{{- with .Values.ausf}}
{{- if .service.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs-ausf.fullname" $ }}-sbi
  labels:
    {{- include "open5gs-ausf.labels" $ | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "open5gs-ausf.selectorLabels" $ | nindent 4 }}
{{- end}}
{{- end}}