apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ $.Values.global.sbinetwork.name }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "bridge",
          "capabilities": { "ips": true },
          "bridge": "sbi0",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }'