{{- with .Values.sepp }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs-sepp.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.name }}
data:
  sepp.yaml: |
    logger:
      {{- toYaml .logger | nindent 8 }}
    global:
      max:
        ue: {{ $.Values.global.ue.max }} # The number of UE can be increased depending on memory size.
    #    peer: 64

    sepp:
      default:
      tls:
        server:
          private_key: {{ $.Values.global.basedir }}/tls/sepp1.key
          cert: {{ $.Values.global.basedir }}/tls/sepp1.crt
        client:
          cacert: {{ $.Values.global.basedir }}/tls/ca.crt
      sbi:
        server:
          - address: {{ .sbinet.ip }}
            port: {{ .sbinet.port }}
            advertise: {{ include "open5gs-sepp.fullname" $ }}-sbi
        client:
    #      nrf:
    #        - uri: http://127.0.0.10:7777
          scp:
            - uri: http://{{ $.Values.global.scp.sbinet.ip }}:{{ $.Values.global.scp.sbinet.port }}
      n32:
        server:
          - sender: sepp1.localdomain
            scheme: https
            address: 127.0.1.251
            port: 7777
            n32f:
              scheme: https
              address: 127.0.1.252
              port: 7777
        client:
          sepp:
            - receiver: sepp2.localdomain
              uri: https://sepp2.localdomain:7777
              resolve: 127.0.2.251
              n32f:
                uri: https://sepp2.localdomain:7777
                resolve: 127.0.2.252
{{- end }}
