{{- with .Values.smf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open5gs-smf.fullname" $ }}
  labels:
    {{- include "open5gs-smf.labels" $ | nindent 4 }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "open5gs-smf.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "{{ $.Values.global.n4network.name }}-{{ include "open5gs-smf.fullname" $ }}",
              "interface": "n4",
              "ips": [ "{{ $.Values.global.smf.n4ip }}/{{ $.Values.global.n4network.cidr }}" ]
            },
            { "name": "{{ $.Values.global.n4unetwork.name }}-{{ include "open5gs-smf.fullname" $ }}",
              "interface": "n4u",
              "ips": [ "{{ $.Values.global.smf.n4uip }}/{{ $.Values.global.n4unetwork.cidr }}" ]
            },
            { "name": "{{ $.Values.global.sbinetwork.name }}",
              "interface": "sbi",
              "ips": [ "{{ .sbinet.ip }}/{{ $.Values.global.sbinetwork.cidr }}" ]
            }]'
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "open5gs-smf.labels" $ | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      
      initContainers:
      - name: wait-amf
        {{- with $.Values.global.initcontainers.curl }}
        image: {{ .registry }}/{{ .image }}:{{ .tag }}
        {{- end }}
        imagePullPolicy: {{ .image.pullPolicy }}
        env:
        - name: URIS
          value: http://{{ $.Values.global.amf.sbinet.ip }}:{{ $.Values.global.amf.sbinet.port }}
        command: ['sh', '-c', 'set -x; for uri in $URIS; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $uri --http2-prior-knowledge) -ne 400 ]; do echo waiting for scp; sleep 1; done; done;']
      containers:
      - name: {{ .name }}
        securityContext:
          {{- toYaml .securityContext | nindent 12 }}
        image: "{{ .image.registry }}/{{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - name: smf-sbi
          containerPort: {{ .sbinet.port }}
        - name: n4
          containerPort: 8805
        - name: n4u
          containerPort: 2152
        - name: n4c
          containerPort: 2123
        - name: frdi
          containerPort: 3868
        resources:
          {{- toYaml .resources | nindent 12 }}
        {{- if .livenessProbe.enabled }}
        livenessProbe:
          # Using tcpSocket instead of httpGet because open5gs only support HTTP/2
            tcpSocket:
              port: smf-sbi
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
            successThreshold: {{ .livenessProbe.successThreshold }}
            failureThreshold: {{ .livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .readinessProbe.enabled }}
        readinessProbe:
        # Using tcpSocket instead of httpGet because open5gs only support HTTP/2
          tcpSocket:
            port: smf-sbi
          initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .readinessProbe.timeoutSeconds }}
          successThreshold: {{ .readinessProbe.successThreshold }}
          failureThreshold: {{ .readinessProbe.failureThreshold }}
        {{- end }}
        volumeMounts:
        - mountPath: {{ .volumeMounts.confPath }}
          name: {{ include "open5gs-smf.fullname" $ }}-conf-volume
        - mountPath: {{ .volumeMounts.logPath }}
          name: {{ include "open5gs-smf.fullname" $ }}-log-volume
        command: ["./open5gs-smfd"]
        args: ["-c", "../etc/smf.yaml"]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ include "open5gs-smf.fullname" $ }}-log-volume
        emptyDir: {}
      - name: {{ include "open5gs-smf.fullname" $ }}-conf-volume
        projected:
          sources:
          - configMap:
              name: {{ include "open5gs-smf.fullname" $ }}-configmap
              items:
              - key: smf.yaml
                path: smf.yaml
              - key: frdi_smf.conf
                path: frdi_smf.conf
{{- end }}
