nameOverride: ""
fullnameOverride: ""


udm:
  name: udm
  replicaCount: 1
  image:
    name: irt-xG/open5gs-udm
    pullPolicy: Always
    tag: latest

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    name: udm-sbi
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  volumeMounts:
    mountPath: "/open5gs/install/etc/open5gs"
  
  logger:
    file: /open5gs/install/etc/udm.log
    level: info
