{{- with .Values.nrf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs-nrf.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.name }}
data:
  nrf.yaml: |
    logger:
      {{- toYaml .logger | nindent 8 }}
    global:
      max:
        ue: {{ $.Values.global.ue.max }} # The number of UE can be increased depending on memory size.
    #    peer: 64

    nrf:
      serving:  # 5G roaming requires PLMN in NRF
        - plmn_id:
            mcc: 208
            mnc: 89
      #   - plmn_id:
      #       mcc: 001
      #       mnc: 01
      sbi:
        server:
          - address: {{ .sbinet.ip }}
            port: {{ .sbinet.port }}
    #    client:
    #      nrf:
    #        - uri: http://127.0.0.10:7777
          # scp:
          #   - uri: http://{{ $.Values.global.scp.sbinet.ip }}:{{ $.Values.global.scp.sbinet.port }}
{{- end }}
