{{- with .Values.nrf}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.global.nrf.service.name }}
  labels:
    {{- include "open5gs-nrf.labels" $ | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ $.Values.global.nrf.service.port }}
      targetPort: {{ $.Values.global.nrf.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "open5gs-nrf.selectorLabels" $ | nindent 4 }}
{{- end}}