{{- with .Values.webui}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs-webui.fullname" $ }}-sbi
  labels:
    {{- include "open5gs-webui.labels" $ | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      nodePort: {{ .service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "open5gs-webui.selectorLabels" $ | nindent 4 }}
{{- end}}