{{- with .Values.amf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs-amf.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.name }}
data:
  amf.yaml: |
    logger:
      {{- toYaml .logger | nindent 8 }}
    global:
      max:
        ue: {{ $.Values.global.ue.max }} # The number of UE can be increased depending on memory size.
    #    peer: 64

    amf:
      sbi:
        server:
          - address: {{ .sbinet.ip }}
            port: {{ .sbinet.port }}
        client:
    #      nrf:
    #        - uri: http://127.0.0.10:7777
          scp:
            - uri: http://{{ $.Values.global.scp.sbinet.ip }}:{{ $.Values.global.scp.sbinet.port }}
      ngap:
        server:
          - address: {{ $.Values.global.amf.n2ip }}
      # metrics:
      #   server:
      #     - address: 127.0.0.1
      #       port: 9090
      guami:
        - plmn_id:
          #   mcc: 001
          #   mnc: 01
          # amf_id:
          #   region: 2
          #   set: 1
        - plmn_id:
            mcc: 208
            mnc: 89
          amf_id:
            region: 5
            set: 2
      tai:
        # - plmn_id:
        #     mcc: 001
        #     mnc: 01
        #   tac: 100
        - plmn_id:
            mcc: 208
            mnc: 89
          tac: 1
      plmn_support:
        # - plmn_id:
        #     mcc: 001
        #     mnc: 01
        #   s_nssai:
        #     - sst: 1
        #       sd: 010203
        #     - sst: 1
        - plmn_id:
            mcc: 208
            mnc: 89
          s_nssai:
            - sst: 1
              sd: 0112233
      security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
      network_name:
        full: Open5GS
        short: Next
      amf_name: open5gs-amf0
      time:
    #    t3502:
    #      value: 720   # 12 minutes * 60 = 720 seconds
        t3512:
          value: 540    # 9 minutes * 60 = 540 seconds
{{- end }}
