{{- with .Values.amf}}
{{- if .sbinet.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs-amf.fullname" $ }}-sbi
  labels:
    {{- include "open5gs-amf.labels" $ | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "open5gs-amf.selectorLabels" $ | nindent 4 }}
{{- end}}
{{- end}}