{{- with .Values.upf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open5gs-upf.fullname" $ }}
  labels:
    {{- include "open5gs-upf.labels" $ | nindent 4 }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "open5gs-upf.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "{{ .n3network.name }}-{{ include "open5gs-upf.fullname" $ }}",
              "interface": "n3",
              "ips": [ "{{ .n3ip }}/{{ .n3network.cidr }}" ]
            },
            { "name": "{{ .n4network.name }}-{{ include "open5gs-upf.fullname" $ }}",
              "interface": "n4",
              "ips": [ "{{ .n4ip }}/{{ .n4network.cidr }}" ]
            },
            { "name": "{{ .n6network.name }}-{{ include "open5gs-upf.fullname" $ }}",
              "interface": "n6",
              "ips": [ "{{ .n6ip }}/{{ .n6network.cidr }}" ]
            }]'
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "open5gs-upf.labels" $ | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}

      containers:
      - name: {{ .name }}
        securityContext:
          {{- toYaml .securityContext | nindent 12 }}
        image: "{{ .image.registry }}/{{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - name: n4
          containerPort: 8805
        - name: n3
          containerPort: 2152
        command: ["{{ .volumeMounts.confPath }}/app.sh"]
        resources:
          {{- toYaml .resources | nindent 12 }}
        volumeMounts:
        - mountPath: {{ .volumeMounts.confPath }}
          name: {{ include "open5gs-upf.fullname" $ }}-conf-volume
        - mountPath: {{ .volumeMounts.logPath }}
          name: {{ include "open5gs-upf.fullname" $ }}-log-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ include "open5gs-upf.fullname" $ }}-log-volume
        emptyDir: {}
      - name: {{ include "open5gs-upf.fullname" $ }}-conf-volume
        projected:
          sources:
          - configMap:
              name: {{ include "open5gs-upf.fullname" $ }}-configmap
              items:
              - key: upf.yaml
                path: upf.yaml
              - key: app.sh
                path: app.sh
                mode: 0777

{{- end }}
