{{- with .Values.upf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open5gs-upf.fullname" $ }}
  labels:
    {{- include "open5gs-upf.labels" $ | nindent 4 }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "open5gs-upf.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "{{ $.Values.global.n3network.name }}-{{ include "open5gs-upf.fullname" $ }}",
              "interface": "n3",
              "ips": [ "{{ $.Values.global.upf.n3ip }}/{{ $.Values.global.n3network.cidr }}" ]
            },
            { "name": "{{ $.Values.global.n4network.name }}-{{ include "open5gs-upf.fullname" $ }}",
              "interface": "n4",
              "ips": [ "{{ $.Values.global.upf.n4ip }}/{{ $.Values.global.n4network.cidr }}" ]
            },
            { "name": "{{ $.Values.global.n6network.name }}-{{ include "open5gs-upf.fullname" $ }}",
              "default-route": ["{{ $.Values.global.n6network.gatewayIP }}"],
              "interface": "n6",
              "ips": [ "{{ $.Values.global.upf.n6ip }}/{{ $.Values.global.n6network.cidr }}" ]
            }]'
      labels:
        {{- include "open5gs-upf.labels" $ | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}

      containers:
      - name: {{ .name }}
        securityContext:
          {{- toYaml .securityContext | nindent 12 }}
        image: "{{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - name: n4
          containerPort: 8805
        - name: n3
          containerPort: 2152
        resources:
          {{- toYaml .resources | nindent 12 }}
        volumeMounts:
        - mountPath: {{ .volumeMounts.mountPath }}
          name: {{ include "open5gs-upf.fullname" $ }}-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ include "open5gs-upf.fullname" $ }}-volume
        projected:
          sources:
          - configMap:
              name: {{ include "open5gs-upf.fullname" $ }}-configmap
              items:
              - key: upf.yaml
                value: upf.yaml
              - key: app.sh
                value: app.sh
                mode: 0777

{{- end }}
