{{- if $.Values.global.n3network.enabled}}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ $.Values.global.n3network.name }}-{{ include "open5gs-upf.fullname" $ }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": {{ $.Values.global.n3network.type | quote }},
          "capabilities": { "ips": true },
{{- if eq $.Values.global.n3network.type "ipvlan" }}
          "master": {{ $.Values.global.n3network.masterIf | quote }},
{{- end }}
{{- if eq $.Values.global.n3network.type "host-device" }}
          "device": {{ $.Values.global.n3network.masterIf | quote }},
{{- end }}
{{- if eq $.Values.global.n3network.type "macvlan" }}
          "mode": "bridge",
{{- end }}
{{- if eq $.Values.global.n3network.type "ipvlan" }}
          "mode": "l2",
{{- end }}
          "ipam": {
            "type": "static"
          }
        }
{{- if eq $.Values.global.n3network.type "macvlan" -}}
        , {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
{{- end }}
      ]
    }'
{{- end }}