{{- with .Values.upf }}
{{- if  .n4network.enabled}}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .n4network.name }}-{{ include "open5gs-upf.fullname" $ }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": {{ .n4network.type | quote }},
          "capabilities": { "ips": true },
          "master": {{ .n4network.masterIf | quote }},
{{- if eq .n4network.type "macvlan" }}
          "mode": "bridge",
{{- end }}
{{- if eq .n4network.type "ipvlan" }}
          "mode": "l2",
{{- end }}
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "0.0.0.0/0",
                "gw": "{{ .n4network.gatewayIP }}"
              }
            ]
          }
        }
{{- if eq .n4network.type "macvlan" -}}
        , {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
{{- end }}
      ]
    }'
{{- end }}
{{- end }}