## Common config values for each NF

## Conditions on deployment ##

deployMongoDb: true
deployAmf: true
deployAusf: true
deployBsf: true
deployNrf: true
deployNssf: true
deployPcf: true
deployScp: true
deploySepp: false
deploySmf: true
deployUdm: true
deployUdr: true
deployUpf: false
deployWebui: true

global:
  name: open5gs
  basedir: /open5gs/install/etc
  sbi:
    port: 80
  amf:
    n2ip: 10.1.1.3
    n2port: 38412
  nrf:
    service:
      name: nrf-sbi
      type: ClusterIP
      port: 8000
  scp:
    service:
      name: scp-sbi
      type: ClusterIP
      port: 8000
  smf:
    n4ip: 10.100.50.244
    n4uip: 10.100.50.234
  upf:
    n4ip: 10.100.50.241
    n3ip: 10.1.2.3
    n6ip: 10.10.10.208
  ue:
    max: 1024
    subnet4: 10.45.0.1/16
    subnet6: 2001:db8:cafe::1/48

  initcontainers:
    curl:
      registry: towards5gs
      image: initcurl
      tag: latest
    busybox:
      image: busybox
      tag: "1.32.0"


  mongodb:
    fullnameOverride: "mongodb"
    useStatefulSet: true
    auth:
      enabled: false
    persistence:
      size: 6Gi
      mountPath: /bitnami/mongodb/data/db/
    service:
      name: mongodb
      type: ClusterIP
      port: 27017

  db_uri: mongodb://mongodb/open5gs

  ## Networks inside the CN
  n2network:
    enabled: true
    name: n2network
    type: host-device
    masterIf: ens20
    subnetIP: 10.1.1.0
    cidr: 24
    gatewayIP: 10.1.1.254
    excludeIP: 10.1.1.254
  n3network:
    enabled: true
    name: n3network
    type: host-device
    masterIf: ens21
    subnetIP: 10.1.2.0
    cidr: 24
    gatewayIP: 10.1.2.254
    excludeIP: 10.1.2.254
  n4network:
    enabled: true
    name: n4network
    type: ipvlan
    masterIf: ens18
    subnetIP: 10.100.50.240
    cidr: 29
    gatewayIP: 10.100.50.246
    excludeIP: 10.100.50.246
  n4unetwork:
    enabled: true
    name: n4unetwork
    type: ipvlan
    masterIf: ens18
    subnetIP: 10.100.50.232
    cidr: 29
    gatewayIP: 10.100.50.238
    excludeIP: 10.100.50.238
  n6network:
    enabled: true
    name: n6network
    type: ipvlan
    masterIf: ens18
    subnetIP: 10.10.30.0
    cidr: 24
    gatewayIP: 10.10.30.254
    excludeIP: 10.100.30.254
  n9network:
    enabled: true
    name: n9network
    type: ipvlan
    masterIf: ens18
    subnetIP: 10.100.50.224
    cidr: 29
    gatewayIP: 10.100.50.230
    excludeIP: 10.100.50.230

  



































mongodb:
  fullnameOverride: "mongodb"
  useStatefulSet: true
  auth:
    enabled: false
  persistence:
    size: 6Gi
    mountPath: /bitnami/mongodb/data/db/
  service:
    name: mongodb
    type: ClusterIP
    port: 27017